service: kysyms-backend
frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs18.x

functions:
  NewMessageWebhook:
    handler: src/handler.newMessageWebhook
    events:
      - httpApi:
          path: /
          method: post
    timeout: 30
  SignUp:
    handler: src/handler.signup
    events:
      - httpApi:
          path: /signup
          method: post
