service: kysyms-backend
frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: src/handler.newMessageWebhook
    events:
      - httpApi:
          path: /
          method: post
